version: '3'
services:
  nginx:
    image: nginx:stable
    container_name: wp-nginx
    ports:
      - '${NGINX_HOST_PORT}:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
      - ./wordpress:/var/www/html
    restart: always
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - wordpress
  wordpress:
     image: wordpress:php8.0-fpm
     expose:
       - '9000'
     volumes:
       - ./wordpress:/var/www/html
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: ${MYSQL_USER}
       WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
       WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
       TZ: Asia/Tokyo
     container_name: wordpress
     depends_on:
       - db
  db:
     image: mariadb:latest
     restart: always
     volumes:
       -  ./db_data:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
       TZ: Asia/Tokyo
     ports:
       - 3306:3306
     container_name: wp-db
volumes:
  db_data:
